### ISSUE TITLE
cputop fails on Alderlake

### ISSUE THREAD

**Issue by aayasin** [andikleen/pmu-tools#451] opened 2023-04-13 15:17 UTC
I see this after offlining some CPUs, e.g.:

    $ ./cputop 'type == "atom"' offline

They cannot be turned on:

    $ ./pmu-tools/cputop 'type == "atom"' online
    Traceback (most recent call last):
      File "/iusers/ayasin/perf-tools/./pmu-tools/cputop", line 93, in <module>
        if m.group(2):
    AttributeError: 'NoneType' object has no attribute 'group'

Even worse, toplev starts to fail:

    $ PERF=../perf ./pmu-tools/toplev --version
    Traceback (most recent call last):
      File "/iusers/ayasin/perf-tools/./pmu-tools/toplev", line 3720, in <module>
        runner_list = init_runner_list()
      File "/iusers/ayasin/perf-tools/./pmu-tools/toplev", line 3697, in init_runner_list
        cpu_list = get_cpu_list(j)
      File "/iusers/ayasin/perf-tools/./pmu-tools/toplev", line 3669, in get_cpu_list
        return [k for k in read_cpus(fn) if use_cpu(k)]
      File "/iusers/ayasin/perf-tools/./pmu-tools/toplev", line 3658, in read_cpus
        return parse_cpu_list(cpus.readline())
      File "/iusers/ayasin/perf-tools/./pmu-tools/toplev", line 3649, in parse_cpu_list
        if m.group(2):
    AttributeError: 'NoneType' object has no attribute 'group'

**Comment by andikleen** [comment] 2023-06-20 20:48
Does it work after ab497ac5d43f256bd67f21bcde5f2901226cac64 ?

**Comment by andikleen** [comment] 2023-07-16 02:14
Duplicate of #461

**Closed by andikleen** 2023-07-16 02:14 UTC
